blank_issues_enabled: false
contact_links:
  - name: ⚠ GitHub Issues Migration in progress ⚠
    url: https://discuss.python.org/t/github-issues-migration-status-update/14573
    about: Check status updates on the migration
