name: Docs

on:
  #push:
  #  branches:
  #  - 'main'
  #  - '3.10'
  #  - '3.9'
  #  - '3.8'
  #  - '3.7'
  #  paths:
  #  - 'Doc/**'
  pull_request:
    branches:
    - 'main'
    - '3.10'
    - '3.9'
    - '3.8'
    - '3.7'
    paths:
    - 'Doc/**'
    - 'Misc/**'

jobs:
  build_doc:
    name: 'Docs'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Register Sphinx problem matcher
      run: echo "::add-matcher::.github/problem-matchers/sphinx.json"
    - name: 'Install Dependencies'
      run: sudo ./.github/workflows/posix-deps-apt.sh && sudo apt-get install wamerican
    - name: 'Configure CPython'
      run: ./configure --with-pydebug
    - name: 'Build CPython'
      run: make -j4
    - name: 'Install build dependencies'
      run: make -C Doc/ PYTHON=../python venv
    - name: 'Build documentation'
      run: xvfb-run make -C Doc/ PYTHON=../python SPHINXOPTS="-q -W --keep-going -j4" doctest html
    - name: 'Upload'
      uses: actions/upload-artifact@v2.2.4
      with:
        name: doc-html
        path: Doc/build/html
